version: '3.7'
services:
    databases:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        networks: 
            - server-db
        ports: 
        - "3306:3306"
        environment:
        - MYSQL_ROOT_PASSWORD=123456
    server:
        image: server-image
        networks: 
            - server-db
            - server-client
        ports:
        - "8090:8090"
        volumes:
            - type: volume
              source: server-data
              target: /usr/src/app/FaceD
    client:
        image: client-image
        networks: 
            - server-client
        ports:
        - "8093:8093"
        restart: always
        volumes:
            - type: volume
              source: client-data
              target: /usr/src/app/FaceD 
networks: 
    server-db:
        driver: bridge
    server-client:
        driver: bridge
volumes:
    client-data:
    server-data: